### ISSUE TITLE
Add money to student portfolio

### ISSUE THREAD

**Issue by americac** [rubyforgood/stocks-in-the-future#143] opened 2024-05-31 14:40 UTC
# Summary

Adding money to an account

    1. Let's create a simple admin page so, for our own sakes, we can arbitrarily add money to accounts for our own testing purposes
    2. After that simple add money page exists, maybe we lock it down?
    3. If we have capacity, we then iterate on this so that teachers can add a perfect attendance week for a student and that then adds money to a student's account. How much money? We don't know. Let's make it configurable since it seems likely to change

# Criteria for Completion

 - [ ] When an admin navigates to a student dashboard a "Add funds" button is present
 - [ ] When the admin clicks on "Add Funds" a form will be available with a field to add funds
 - [ ] When saving the funds, it enters a deposit transaction with the funds amount in the portfolio_transactions table
 - [ ] The admin should see the cash balance increase by the amount added

**Comment by jonny5** [comment] 2024-05-31 17:07
closing, dupe of #142

**Closed by jonny5** 2024-05-31 17:07 UTC
